### PR TITLE
Feature/make installable

### PR DESCRIPTION
**Pull request by boba-and-beer**
I moved everything into modules to make it PIP Installable. 
I currently have created a package which can be found here: https://pypi.org/project/clip-by-openai/.
This should make CLIP a lot easier to use for individuals looking to test it out. Furthermore, I have also added the model to VectorHub, an open-source repository for vector search models I maintain, which can be found here:
https://hub.getvectorai.com/model/text_image%2Fclip

The link may be useful for people looking for low barriers to entry when trying out CLIP.

### CODE REVIEW

**Comment by jongwook** [comment]
Hi, thanks for your interest in CLIP and packaging it for easier use.

We cannot merge this PR at this state because it has a few issues we'd like to fix, such as the overly complex `.gitignore`, unintended audience and supported Python versions in `setup.py`, recommendation of installing pytorch and cudatoolkit via PIP in `README.md`, and multiple references to your company.

We are actually working on an update to make this package PIP-installable, and we are planning to make it work this way:

```
pip install git+https://github.com/openai/CLIP.git
```

so that we don't have to worry about versioning for now.

Would you like me to make edits directly on this branch before merging this PR, or would you rather close this PR entirely?

**Comment by boba-and-beer** [comment]
That's a good way to go about it. I would like you to make edits on this branch if possible. Would love to track how this goes and make whatever small contribution I can for CLIP. Found the paper and blog quite insightful and I'm surprised with the results! I have also removed all mentions of VectorAI from this PR.

**Comment by boba-and-beer** [comment]
Closing for now.

**Comment by jamt9000** [comment]
@jongwook since it seems to work fine for pytorch 1.7 could you relax the requirements to

```
pytorch~=1.7
torchvision==0.8.*
```

so that pip install works?

**Comment by haltakov** [comment]
> @jongwook since it seems to work fine for pytorch 1.7 could you relax the requirements to
> 
> ```
> pytorch~=1.7
> torchvision==0.8.*
> ```
> 
> so that pip install works? (torchvision from source ends up having version number [0.8.0a0](https://github.com/pytorch/vision/blob/v0.8.1/setup.py#L32) hence the `*`)

I did some experiments with torch==1.7.0 and it fails in very subtle ways. Most of the time everything seems fine, but there is some very strange behavior at other times. If you are interested I can create a small demo showing the behavior.

**Comment by jamt9000** [comment]
@haltakov I see - yes it would be good to know how it fails

**Comment by brunodoamaral** [comment]
> @haltakov I see - yes it would be good to know how it fails

See https://github.com/openai/CLIP/issues/13. I had the same strange behavior reported in this issue.

**Comment by haltakov** [comment]
> @haltakov I see - yes it would be good to know how it fails

Here the experiments on Colab:

- 1.7.0: https://colab.research.google.com/drive/1KcHMeI2N-FFthMEYip3A1ZNbccdRK4XR?usp=sharing
- 1.7.1: https://colab.research.google.com/drive/1h3pyWaZ0gA4DYWoip49W1skBmkxZ_gDC?usp=sharing

**Pull request merged**
