### PR TITLE
Fix PyTorch version check

### PR DESCRIPTION
**Pull request by bryant1410**
So the check works fine with PyTorch 1.10.0.

### CODE REVIEW

**Comment by jiahuei** [comment]
I would like to suggest changing 
`if [int(n) for n in torch.__version__.split(".")] < [1, 7, 1]:`
to
`if [int(n.split("+")[0]) for n in torch.__version__.split(".")] < [1, 7, 1]:`

so that it would work for versions with extra flags such as `1.10.0+cu102` or `1.10.0+cpu`

**Comment by elliottzheng** [comment]
as mentioned by @jiahuei , I got the error when using the latest clip 
```
ValueError: invalid literal for int() with base 10: 'dev20210803'`
```
as my torch version is `1.10.0.dev20210803+cu111`

**Comment by jiahuei** [comment]
@elliottzheng the version check should work now

**Comment by elliottzheng** [comment]
@jiahuei great

**Comment by alex8937** [comment]
Got a problem when torch version is `1.9.0a0+2ecb2c7`

**Pull request merged**
